import { Repository, createRepository } from './repository'

class CardapioRepository extends Repository {
  endpoint = 'v1/cardapio'

  getCategories () {
    return Promise.resolve({
      data: [{
        id: 1,
        nome: 'Doces',
        grupo: 'Tortas',
        layout: 'Padr\u00E3o',
        Lojas_idLojas: 1,
        permiteCombinacao: 0,
        quantidadeCombinacoes: null,
        created_at: '2018-09-12 18:11:13',
        updated_at: '2018-09-12 18:11:13',
        deleted_at: null
      }, {
        id: 2,
        nome: 'Tortas Salgadas / Quiches',
        grupo: 'Tortas',
        layout: 'Padr\u00E3o',
        Lojas_idLojas: 1,
        permiteCombinacao: 0,
        quantidadeCombinacoes: null,
        created_at: '2018-09-12 18:11:28',
        updated_at: '2019-01-05 17:23:21',
        deleted_at: null
      }, {
        id: 3,
        nome: 'Tradicionais',
        grupo: 'Salgados',
        layout: 'Padr\u00E3o',
        Lojas_idLojas: 1,
        permiteCombinacao: 0,
        quantidadeCombinacoes: null,
        created_at: '2018-09-12 18:12:07',
        updated_at: '2018-12-11 13:00:40',
        deleted_at: null
      }, {
        id: 4,
        nome: 'Tradicionais',
        grupo: 'Doces',
        layout: 'Padr\u00E3o',
        Lojas_idLojas: 1,
        permiteCombinacao: 0,
        quantidadeCombinacoes: null,
        created_at: '2018-09-12 18:12:16',
        updated_at: '2018-12-10 13:26:36',
        deleted_at: null
      }, {
        id: 5,
        nome: 'Folhados',
        grupo: 'Salgados',
        layout: 'Padr\u00E3o',
        Lojas_idLojas: 1,
        permiteCombinacao: 0,
        quantidadeCombinacoes: null,
        created_at: '2018-09-12 18:12:26',
        updated_at: '2018-12-11 13:00:57',
        deleted_at: null
      }, {
        id: 6,
        nome: 'Diet',
        grupo: 'Doces',
        layout: 'Padr\u00E3o',
        Lojas_idLojas: 1,
        permiteCombinacao: 0,
        quantidadeCombinacoes: null,
        created_at: '2018-09-12 18:12:38',
        updated_at: '2018-12-10 13:26:52',
        deleted_at: null
      }, {
        id: 7,
        nome: 'Diet',
        grupo: 'Tortas',
        layout: 'Padr\u00E3o',
        Lojas_idLojas: 1,
        permiteCombinacao: 0,
        quantidadeCombinacoes: null,
        created_at: '2018-12-10 12:05:24',
        updated_at: '2018-12-10 12:05:24',
        deleted_at: null
      }]
    })
  }

  getProducts (categoryId) {
    return Promise.resolve({
      data: [{
        data: {
          id: 118,
          nome: 'Bolo Hungaro (sem gl\u00FAten)',
          preco: 85,
          imagem: '1-118.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-12-03 12:51:14',
          updated_at: '2019-03-08 15:15:54',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: '(N\u00E3o recomendado para cel\u00EDacos), Cacau 100%, Chocolate meio amargo, Ovos.'
      }, {
        data: {
          id: 1,
          nome: 'Monte sua Torta',
          preco: 59.9,
          imagem: '1-1.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-12 18:34:15',
          updated_at: '2019-04-18 10:29:57',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [{
          data: {
            id: 3,
            nome: 'Interior',
            'visibilidade': 'Essencial Vis\u00EDvel',
            'obrigatorio': 1,
            'quantidade_min': 1,
            'quantidade_max': 1,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 18:17:34',
            updated_at: '2019-04-18 10:29:57',
            deleted_at: null,
            'pivot': { 'Produtos_idProdutos': 1, 'Multiplos_idMultiplos': 3 }
          },
          'isMultipleChoice': false,
          ingredientes: [{
            id: 68,
            nome: 'P\u00E3o de L\u00F3 com Nozes trituradas',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 17:54:53',
            updated_at: '2018-12-04 17:54:53',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 3, 'Ingredientes_idIngredientes': 68, id: 9, 'valor': null }
          }, {
            id: 33,
            nome: 'P\u00E3o de L\u00F3 de Baunilha (Branco)',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-03 11:37:34',
            updated_at: '2018-12-04 17:53:26',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 3, 'Ingredientes_idIngredientes': 33, id: 10, 'valor': null }
          }, {
            id: 38,
            nome: 'P\u00E3o de L\u00F3 de Canela (Estilo churros)',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-03 11:40:08',
            updated_at: '2018-12-04 17:54:19',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 3, 'Ingredientes_idIngredientes': 38, id: 11, 'valor': null }
          }, {
            id: 30,
            nome: 'P\u00E3o de L\u00F3 de chocolate',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-03 11:36:22',
            updated_at: '2018-12-03 11:36:22',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 3, 'Ingredientes_idIngredientes': 30, id: 12, 'valor': null }
          }],
          'produto': [{
            id: 1,
            nome: 'Monte sua Torta',
            preco: 59.9,
            imagem: '1-1.jpg',
            status: 'Dispon\u00EDvel',
            codigo_PDV: null,
            promocionar: 0,
            valorPromocao: null,
            Cat_produtos_idCat_produtos: 1,
            Lojas_idLojas: 1,
            domingo: 1,
            segunda: 1,
            terca: 1,
            quarta: 1,
            quinta: 1,
            sexta: 1,
            sabado: 1,
            disponibilidade: 'Sempre Dispon\u00EDvel',
            inicio_periodo1: null,
            termino_periodo1: null,
            inicio_periodo2: null,
            termino_periodo2: null,
            created_at: '2018-09-12 18:34:15',
            updated_at: '2019-04-18 10:29:57',
            deleted_at: null,
            tempo_producao: null,
            unidade_medida: 'kg',
            minimo_unidade: 1,
            intervalo: 0.5,
            'pivot': { 'Multiplos_idMultiplos': 3, 'Produtos_idProdutos': 1 }
          }]
        }, {
          data: {
            id: 4,
            nome: 'Recheios',
            'visibilidade': 'Essencial Vis\u00EDvel',
            'obrigatorio': 1,
            'quantidade_min': 1,
            'quantidade_max': 2,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 18:17:34',
            updated_at: '2019-04-18 10:29:57',
            deleted_at: null,
            'pivot': { 'Produtos_idProdutos': 1, 'Multiplos_idMultiplos': 4 }
          },
          'isMultipleChoice': true,
          ingredientes: [{
            id: 69,
            nome: 'Baba de mo\u00E7a com nozes',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 17:56:02',
            updated_at: '2018-12-04 17:56:02',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 69, id: 13, 'valor': null }
          }, {
            id: 70,
            nome: 'Brigadeiro',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 17:57:34',
            updated_at: '2018-12-04 17:57:34',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 70, id: 14, 'valor': null }
          }, {
            id: 36,
            nome: 'Chocolate ao leite',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-03 11:38:38',
            updated_at: '2018-12-03 11:38:38',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 36, id: 15, 'valor': null }
          }, {
            id: 71,
            nome: 'Chocolate com morango',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 17:58:24',
            updated_at: '2018-12-04 17:58:24',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 71, id: 16, 'valor': null }
          }, {
            id: 72,
            nome: 'Chocolate com nozes',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 17:58:42',
            updated_at: '2018-12-04 17:58:42',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 72, id: 17, 'valor': null }
          }, {
            id: 74,
            nome: 'Chocolate com sonho de valsa',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 17:59:02',
            updated_at: '2018-12-04 17:59:02',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 74, id: 18, 'valor': null }
          }, {
            id: 57,
            nome: 'Chocolate meio amargo',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-03 11:48:37',
            updated_at: '2018-12-03 11:48:37',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 57, id: 19, 'valor': null }
          }, {
            id: 26,
            nome: 'Creme de baunilha',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-09-13 13:15:32',
            updated_at: '2018-12-04 18:00:04',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 26, id: 20, 'valor': null }
          }, {
            id: 78,
            nome: 'Creme de maracuj\u00E1',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 18:00:21',
            updated_at: '2018-12-04 18:00:21',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 78, id: 21, 'valor': null }
          }, {
            id: 86,
            nome: 'Creme de morango',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 18:12:45',
            updated_at: '2018-12-04 18:12:45',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 86, id: 22, 'valor': null }
          }, {
            id: 99,
            nome: 'Morango(em peda\u00E7os)',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2019-03-08 10:20:14',
            updated_at: '2019-03-08 10:20:14',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 99, id: 62, 'valor': null }
          }, {
            id: 87,
            nome: 'Mousse de chocolate',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 18:13:22',
            updated_at: '2018-12-04 18:13:22',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 87, id: 23, 'valor': null }
          }, {
            id: 88,
            nome: 'Mousse de lim\u00E3o',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 18:13:48',
            updated_at: '2018-12-04 18:13:48',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 88, id: 24, 'valor': null }
          }, {
            id: 89,
            nome: 'Mousse de maracuj\u00E1',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 18:14:03',
            updated_at: '2018-12-04 18:14:03',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 89, id: 25, 'valor': null }
          }, {
            id: 25,
            nome: 'Nozes',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-09-13 13:14:47',
            updated_at: '2018-09-13 13:15:09',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 25, id: 26, 'valor': null }
          }, {
            id: 79,
            nome: 'Prest\u00EDgio',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 18:00:58',
            updated_at: '2018-12-04 18:00:58',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 79, id: 27, 'valor': null }
          }, {
            id: 37,
            nome: 'Suflair',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-03 11:38:59',
            updated_at: '2018-12-03 11:38:59',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 37, id: 28, 'valor': null }
          }, {
            id: 80,
            nome: 'Suflair com morango',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 18:01:23',
            updated_at: '2018-12-04 18:01:23',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 80, id: 29, 'valor': null }
          }, {
            id: 60,
            nome: 'Trufa de chocolate ao Leite',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-03 11:49:40',
            updated_at: '2018-12-03 11:49:40',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 60, id: 30, 'valor': null }
          }, {
            id: 81,
            nome: 'Trufa de chocolate meio amargo',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 18:02:01',
            updated_at: '2018-12-04 18:02:01',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Ingredientes_idIngredientes': 81, id: 31, 'valor': null }
          }],
          'produto': [{
            id: 1,
            nome: 'Monte sua Torta',
            preco: 59.9,
            imagem: '1-1.jpg',
            status: 'Dispon\u00EDvel',
            codigo_PDV: null,
            promocionar: 0,
            valorPromocao: null,
            Cat_produtos_idCat_produtos: 1,
            Lojas_idLojas: 1,
            domingo: 1,
            segunda: 1,
            terca: 1,
            quarta: 1,
            quinta: 1,
            sexta: 1,
            sabado: 1,
            disponibilidade: 'Sempre Dispon\u00EDvel',
            inicio_periodo1: null,
            termino_periodo1: null,
            inicio_periodo2: null,
            termino_periodo2: null,
            created_at: '2018-09-12 18:34:15',
            updated_at: '2019-04-18 10:29:57',
            deleted_at: null,
            tempo_producao: null,
            unidade_medida: 'kg',
            minimo_unidade: 1,
            intervalo: 0.5,
            'pivot': { 'Multiplos_idMultiplos': 4, 'Produtos_idProdutos': 1 }
          }]
        }, {
          data: {
            id: 5,
            nome: 'Cobertura',
            'visibilidade': 'Essencial Vis\u00EDvel',
            'obrigatorio': 1,
            'quantidade_min': 1,
            'quantidade_max': 1,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 18:17:34',
            updated_at: '2019-04-18 10:29:57',
            deleted_at: null,
            'pivot': { 'Produtos_idProdutos': 1, 'Multiplos_idMultiplos': 5 }
          },
          'isMultipleChoice': false,
          ingredientes: [{
            id: 36,
            nome: 'Chocolate ao leite',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-03 11:38:38',
            updated_at: '2018-12-03 11:38:38',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 5, 'Ingredientes_idIngredientes': 36, id: 33, 'valor': null }
          }, {
            id: 82,
            nome: 'Chocolate ao leite com nozes',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 18:02:58',
            updated_at: '2018-12-04 18:02:58',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 5, 'Ingredientes_idIngredientes': 82, id: 34, 'valor': null }
          }, {
            id: 52,
            nome: 'Chocolate branco',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-03 11:46:06',
            updated_at: '2018-12-03 11:46:06',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 5, 'Ingredientes_idIngredientes': 52, id: 35, 'valor': null }
          }, {
            id: 83,
            nome: 'Chocolate branco com nozes',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 18:03:36',
            updated_at: '2018-12-04 18:03:36',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 5, 'Ingredientes_idIngredientes': 83, id: 36, 'valor': null }
          }, {
            id: 71,
            nome: 'Chocolate com morango',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 17:58:24',
            updated_at: '2018-12-04 17:58:24',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 5, 'Ingredientes_idIngredientes': 71, id: 37, 'valor': null }
          }, {
            id: 84,
            nome: 'Chocolate com suspiro',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 18:04:01',
            updated_at: '2018-12-04 18:06:02',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 5, 'Ingredientes_idIngredientes': 84, id: 38, 'valor': null }
          }, {
            id: 27,
            nome: 'Doce de Leite',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-09-13 13:15:45',
            updated_at: '2018-09-13 13:15:45',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 5, 'Ingredientes_idIngredientes': 27, id: 39, 'valor': null }
          }, {
            id: 73,
            nome: 'Frutas da esta\u00E7\u00E3o',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 1,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 17:58:42',
            updated_at: '2018-12-04 18:06:53',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 5, 'Ingredientes_idIngredientes': 73, id: 40, 'valor': null }
          }, {
            id: 75,
            nome: 'Frutas vermelhas',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 1,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 17:59:02',
            updated_at: '2018-12-04 18:07:22',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 5, 'Ingredientes_idIngredientes': 75, id: 41, 'valor': 35.1 }
          }, {
            id: 45,
            nome: 'Ganache de chocolate',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-03 11:42:54',
            updated_at: '2018-12-03 11:42:54',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 5, 'Ingredientes_idIngredientes': 45, id: 42, 'valor': null }
          }, {
            id: 41,
            nome: 'Marshmallow',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-03 11:41:07',
            updated_at: '2018-12-03 11:41:07',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 5, 'Ingredientes_idIngredientes': 41, id: 32, 'valor': null }
          }, {
            id: 25,
            nome: 'Nozes',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-09-13 13:14:47',
            updated_at: '2018-09-13 13:15:09',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 5, 'Ingredientes_idIngredientes': 25, id: 43, 'valor': 6 }
          }, {
            id: 76,
            nome: 'Pasta americana',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 4,
            Lojas_idLojas: 1,
            created_at: '2018-12-04 17:59:02',
            updated_at: '2018-12-04 18:07:49',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 5, 'Ingredientes_idIngredientes': 76, id: 44, 'valor': 34 }
          }],
          'produto': [{
            id: 1,
            nome: 'Monte sua Torta',
            preco: 59.9,
            imagem: '1-1.jpg',
            status: 'Dispon\u00EDvel',
            codigo_PDV: null,
            promocionar: 0,
            valorPromocao: null,
            Cat_produtos_idCat_produtos: 1,
            Lojas_idLojas: 1,
            domingo: 1,
            segunda: 1,
            terca: 1,
            quarta: 1,
            quinta: 1,
            sexta: 1,
            sabado: 1,
            disponibilidade: 'Sempre Dispon\u00EDvel',
            inicio_periodo1: null,
            termino_periodo1: null,
            inicio_periodo2: null,
            termino_periodo2: null,
            created_at: '2018-09-12 18:34:15',
            updated_at: '2019-04-18 10:29:57',
            deleted_at: null,
            tempo_producao: null,
            unidade_medida: 'kg',
            minimo_unidade: 1,
            intervalo: 0.5,
            'pivot': { 'Multiplos_idMultiplos': 5, 'Produtos_idProdutos': 1 }
          }]
        }],
        ingredientes: 'Escolha: Interior, Escolha: Recheios, Escolha: Cobertura'
      }, {
        data: {
          id: 108,
          nome: 'Tartelette',
          preco: 65.9,
          imagem: '4-108.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 13:11:21',
          updated_at: '2019-03-08 15:07:59',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [{
          data: {
            id: 1,
            nome: 'Base',
            'visibilidade': 'Essencial Vis\u00EDvel',
            'obrigatorio': 1,
            'quantidade_min': 1,
            'quantidade_max': 1,
            Lojas_idLojas: 1,
            created_at: '2018-12-03 12:56:05',
            updated_at: '2019-03-08 15:07:59',
            deleted_at: null,
            'pivot': { 'Produtos_idProdutos': 108, 'Multiplos_idMultiplos': 1 }
          },
          'isMultipleChoice': false,
          ingredientes: [{
            id: 67,
            nome: 'Farinha de trigo amanteigada',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 2,
            Lojas_idLojas: 1,
            created_at: '2018-12-03 11:53:16',
            updated_at: '2018-12-03 11:53:16',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 1, 'Ingredientes_idIngredientes': 67, id: 2, 'valor': null }
          }, {
            id: 65,
            nome: 'Farinha de trigo Integral',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 2,
            Lojas_idLojas: 1,
            created_at: '2018-12-03 11:52:35',
            updated_at: '2018-12-03 11:52:35',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 1, 'Ingredientes_idIngredientes': 65, id: 3, 'valor': null }
          }],
          'produto': [{
            id: 108,
            nome: 'Tartelette',
            preco: 65.9,
            imagem: '4-108.jpg',
            status: 'Dispon\u00EDvel',
            codigo_PDV: null,
            promocionar: 0,
            valorPromocao: null,
            Cat_produtos_idCat_produtos: 1,
            Lojas_idLojas: 1,
            domingo: 1,
            segunda: 1,
            terca: 1,
            quarta: 1,
            quinta: 1,
            sexta: 1,
            sabado: 1,
            disponibilidade: 'Sempre Dispon\u00EDvel',
            inicio_periodo1: null,
            termino_periodo1: null,
            inicio_periodo2: null,
            termino_periodo2: null,
            created_at: '2018-09-13 13:11:21',
            updated_at: '2019-03-08 15:07:59',
            deleted_at: null,
            tempo_producao: null,
            unidade_medida: 'kg',
            minimo_unidade: 1,
            intervalo: 0.5,
            'pivot': { 'Multiplos_idMultiplos': 1, 'Produtos_idProdutos': 108 }
          }]
        }, {
          data: {
            id: 2,
            nome: 'Sabor',
            'visibilidade': 'Essencial Vis\u00EDvel',
            'obrigatorio': 1,
            'quantidade_min': 1,
            'quantidade_max': 1,
            Lojas_idLojas: 1,
            created_at: '2018-12-03 12:56:05',
            updated_at: '2019-03-08 15:07:59',
            deleted_at: null,
            'pivot': { 'Produtos_idProdutos': 108, 'Multiplos_idMultiplos': 2 }
          },
          'isMultipleChoice': false,
          ingredientes: [{
            id: 94,
            nome: 'Banana com canela',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 1,
            Lojas_idLojas: 1,
            created_at: '2019-02-12 15:17:49',
            updated_at: '2019-02-12 15:17:49',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 2, 'Ingredientes_idIngredientes': 94, id: 58, 'valor': null }
          }, {
            id: 3,
            nome: 'Lim\u00E3o',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 1,
            Lojas_idLojas: 1,
            created_at: '2018-09-13 10:39:15',
            updated_at: '2018-09-13 10:39:30',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 2, 'Ingredientes_idIngredientes': 3, id: 4, 'valor': null }
          }, {
            id: 95,
            nome: 'Ma\u00E7\u00E3 com canela',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 1,
            Lojas_idLojas: 1,
            created_at: '2019-02-12 15:18:11',
            updated_at: '2019-02-12 15:18:11',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 2, 'Ingredientes_idIngredientes': 95, id: 59, 'valor': null }
          }, {
            id: 4,
            nome: 'Maracuj\u00E1',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 1,
            Lojas_idLojas: 1,
            created_at: '2018-09-13 10:41:11',
            updated_at: '2018-09-13 10:41:11',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 2, 'Ingredientes_idIngredientes': 4, id: 6, 'valor': null }
          }, {
            id: 2,
            nome: 'Morango',
            status: 1,
            preco: 0,
            codigo_PDV: null,
            'Cat_ingredientes_idCat_ingredientes': 1,
            Lojas_idLojas: 1,
            created_at: '2018-09-13 10:39:02',
            updated_at: '2018-09-13 10:39:02',
            deleted_at: null,
            'pivot': { 'Multiplos_idMultiplos': 2, 'Ingredientes_idIngredientes': 2, id: 5, 'valor': null }
          }],
          'produto': [{
            id: 108,
            nome: 'Tartelette',
            preco: 65.9,
            imagem: '4-108.jpg',
            status: 'Dispon\u00EDvel',
            codigo_PDV: null,
            promocionar: 0,
            valorPromocao: null,
            Cat_produtos_idCat_produtos: 1,
            Lojas_idLojas: 1,
            domingo: 1,
            segunda: 1,
            terca: 1,
            quarta: 1,
            quinta: 1,
            sexta: 1,
            sabado: 1,
            disponibilidade: 'Sempre Dispon\u00EDvel',
            inicio_periodo1: null,
            termino_periodo1: null,
            inicio_periodo2: null,
            termino_periodo2: null,
            created_at: '2018-09-13 13:11:21',
            updated_at: '2019-03-08 15:07:59',
            deleted_at: null,
            tempo_producao: null,
            unidade_medida: 'kg',
            minimo_unidade: 1,
            intervalo: 0.5,
            'pivot': { 'Multiplos_idMultiplos': 2, 'Produtos_idProdutos': 108 }
          }]
        }],
        ingredientes: 'Escolha: Base, Escolha: Sabor, Creme de baunilha, '
      }, {
        data: {
          id: 7,
          nome: 'Torta Alem\u00E3',
          preco: 59.9,
          imagem: '1-7.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:21:00',
          updated_at: '2019-04-29 22:13:02',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: 'Creme holand\u00EAs, Ganache de chocolate, Tubetes de chocolate.'
      }, {
        data: {
          id: 11,
          nome: 'Torta Cascata Branca',
          preco: 65.9,
          imagem: null,
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:22:08',
          updated_at: '2018-12-11 12:14:52',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 46,
          nome: 'Torta Comemorativa (pasta americana)',
          preco: 93.9,
          imagem: '1-46.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:34:57',
          updated_at: '2018-12-11 12:33:58',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'Customize sua torta enviando sua foto para o e-mail',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 16,
          nome: 'Torta Crocante de Nozes',
          preco: 65.9,
          imagem: '1-16.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:24:40',
          updated_at: '2019-04-04 21:48:11',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: 'P\u00E3o de L\u00F3 de Baunilha (Branco), Creme de Nozes, Chocolate branco, Nozes trituradas, Leite condensado.'
      }, {
        data: {
          id: 8,
          nome: 'Torta de Ameixa c/ Doce de Leite',
          preco: 59.9,
          imagem: '1-8.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:21:16',
          updated_at: '2019-03-08 10:39:01',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 10,
          nome: 'Torta de Brigadeiro',
          preco: 65.9,
          imagem: '1-10.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:21:54',
          updated_at: '2018-12-09 23:27:16',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: 'P\u00E3o de L\u00F3 de chocolate, Creme de brigadeiro, Chocolate meio amargo, Confete de brigadeiro.'
      }, {
        data: {
          id: 13,
          nome: 'Torta de Chantilly c/ Morango',
          preco: 65.9,
          imagem: null,
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:22:54',
          updated_at: '2018-12-11 12:14:36',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 15,
          nome: 'Torta de Chocolate',
          preco: 65.9,
          imagem: null,
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:23:26',
          updated_at: '2018-12-11 12:14:38',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 116,
          nome: 'Torta de Chocolate ao Rum',
          preco: 65.9,
          imagem: '1-116.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-12-03 12:39:57',
          updated_at: '2018-12-09 23:44:52',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: 'P\u00E3o de L\u00F3 de chocolate, Creme de chocolate, Leite com Rum, Ganache de chocolate.'
      }, {
        data: {
          id: 40,
          nome: 'Torta de Churros',
          preco: 65.9,
          imagem: '1-40.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:31:33',
          updated_at: '2018-12-10 14:39:12',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: 'P\u00E3o de L\u00F3 de Canela (Estilo churros), Leite condensado, Canela.'
      }, {
        data: {
          id: 21,
          nome: 'Torta de Frutas',
          preco: 65.9,
          imagem: '1-21.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:25:58',
          updated_at: '2019-03-09 13:56:39',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 41,
          nome: 'Torta de Frutas Vermelhas',
          preco: 87.9,
          imagem: null,
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:32:41',
          updated_at: '2018-12-11 12:15:21',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 44,
          nome: 'Torta de Kit Kat e M&M',
          preco: 75.9,
          imagem: '1-44.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:33:47',
          updated_at: '2018-12-10 23:51:48',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: 'P\u00E3o de L\u00F3 de Baunilha (Branco), P\u00E3o de L\u00F3 de chocolate, Creme de chocolate, Kit Kat, M&M, Chocolate ao leite.'
      }, {
        data: {
          id: 42,
          nome: 'Torta de Leite Ninho',
          preco: 65.9,
          imagem: '1-42.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:33:02',
          updated_at: '2018-12-09 23:37:43',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 28,
          nome: 'Torta de Morango',
          preco: 65.9,
          imagem: '1-28.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:27:40',
          updated_at: '2018-12-11 00:42:24',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: 'P\u00E3o de L\u00F3 de Baunilha (Branco), Chantily, Morango, Castanha de Caju.'
      }, {
        data: {
          id: 32,
          nome: 'Torta de Nozes',
          preco: 65.9,
          imagem: '1-32.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:28:49',
          updated_at: '2019-03-08 15:31:37',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: 'P\u00E3o de L\u00F3 de Baunilha (Branco), Creme de Nozes, Chocolate branco com nozes, Leite condensado.'
      }, {
        data: {
          id: 33,
          nome: 'Torta de Ouro Branco',
          preco: 59.9,
          imagem: null,
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:29:21',
          updated_at: '2018-12-11 12:15:15',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 34,
          nome: 'Torta de Prestigio',
          preco: 59.9,
          imagem: '1-34.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:29:34',
          updated_at: '2019-01-30 02:27:22',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 17,
          nome: 'Torta Delicia de Morango',
          preco: 65.9,
          imagem: null,
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:24:53',
          updated_at: '2018-12-11 12:14:38',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 47,
          nome: 'Torta Ferrero Rocher',
          preco: 75.9,
          imagem: null,
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:35:59',
          updated_at: '2018-12-11 12:16:01',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 19,
          nome: 'Torta Floresta Branca',
          preco: 65.9,
          imagem: null,
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:25:29',
          updated_at: '2018-12-11 12:14:53',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 20,
          nome: 'Torta Floresta Negra',
          preco: 65.9,
          imagem: '1-20.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:25:44',
          updated_at: '2018-12-09 23:25:04',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 27,
          nome: 'Torta Merengue de Morango',
          preco: 65.9,
          imagem: null,
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:27:31',
          updated_at: '2018-12-11 12:15:01',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 9,
          nome: 'Torta Mesclada Baba de Mo\u00E7a',
          preco: 59.9,
          imagem: '1-9.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:21:29',
          updated_at: '2018-12-09 23:21:16',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: 'P\u00E3o de L\u00F3 de Baunilha (Branco), Creme de Leite, Leite condensado, Marshmallow, Calda de caramelo, Calda de chocolate.'
      }, {
        data: {
          id: 23,
          nome: 'Torta Mesclada de Chocolate',
          preco: 65.9,
          imagem: null,
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:26:28',
          updated_at: '2018-12-11 12:14:56',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 24,
          nome: 'Torta Mesclada de Morango',
          preco: 65.9,
          imagem: null,
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:26:42',
          updated_at: '2018-12-11 12:14:58',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 45,
          nome: 'Torta Naked Cake c/ Frutas Vermelhas',
          preco: 87.9,
          imagem: null,
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:34:18',
          updated_at: '2018-12-11 12:15:59',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 115,
          nome: 'Torta Negresco',
          preco: 59.9,
          imagem: '1-115.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-12-03 12:25:09',
          updated_at: '2018-12-09 23:44:23',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: 'P\u00E3o de L\u00F3 de chocolate, Creme de chocolate, Biscoito negresco, Ganache de chocolate.'
      }, {
        data: {
          id: 117,
          nome: 'Torta Red Velvet',
          preco: 63.9,
          imagem: '1-117.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-12-03 12:45:41',
          updated_at: '2019-10-24 09:55:27',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: 'Massa Especial (Americana), Creme de Cream Cheese.'
      }, {
        data: {
          id: 36,
          nome: 'Torta Sonho de Valsa',
          preco: 59.9,
          imagem: '1-36.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:30:07',
          updated_at: '2018-12-09 23:34:03',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 48,
          nome: 'Torta Suflair',
          preco: 65.9,
          imagem: '1-48.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:36:16',
          updated_at: '2018-12-03 12:35:57',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: 'P\u00E3o de L\u00F3 de chocolate, Creme de chocolate, Suflair, Chocolate ao leite.'
      }, {
        data: {
          id: 49,
          nome: 'Torta Suflair c/ Morango',
          preco: 65.9,
          imagem: '1-49.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:36:41',
          updated_at: '2019-04-04 21:44:51',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 37,
          nome: 'Torta Tr\u00EAs Sabores',
          preco: 59.9,
          imagem: null,
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:30:22',
          updated_at: '2018-12-11 12:15:18',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 38,
          nome: 'Torta Trufa Branca',
          preco: 65.9,
          imagem: null,
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:30:55',
          updated_at: '2018-12-11 12:15:19',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: ''
      }, {
        data: {
          id: 39,
          nome: 'Torta Trufa de Chocolate',
          preco: 65.9,
          imagem: '1-39.jpg',
          status: 'Dispon\u00EDvel',
          codigo_PDV: null,
          promocionar: 0,
          valorPromocao: null,
          Cat_produtos_idCat_produtos: 1,
          Lojas_idLojas: 1,
          domingo: 1,
          segunda: 1,
          terca: 1,
          quarta: 1,
          quinta: 1,
          sexta: 1,
          sabado: 1,
          disponibilidade: 'Sempre Dispon\u00EDvel',
          inicio_periodo1: null,
          termino_periodo1: null,
          inicio_periodo2: null,
          termino_periodo2: null,
          created_at: '2018-09-13 10:31:14',
          updated_at: '2018-12-09 23:36:18',
          deleted_at: null,
          tempo_producao: null,
          unidade_medida: 'kg',
          minimo_unidade: 1,
          intervalo: 0.5
        },
        produtosMultiplos: [],
        categoria: {
          data: {
            id: 1,
            nome: 'Doces',
            grupo: 'Tortas',
            layout: 'Padr\u00E3o',
            Lojas_idLojas: 1,
            permiteCombinacao: 0,
            quantidadeCombinacoes: null,
            created_at: '2018-09-12 18:11:13',
            updated_at: '2018-09-12 18:11:13',
            deleted_at: null
          },
          multiplos: []
        },
        multiplos: [],
        ingredientes: 'P\u00E3o de L\u00F3 de chocolate, Trufa de chocolate ao Leite, Chocolate meio amargo, Ganache de chocolate.'
      }]
    })
  }
}

export default createRepository(CardapioRepository)
